### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by adibiton** [saschakiefer/openui5-bower#12]
Hi All,
Looking at the folder:
https://github.com/openui5/packaged-sap.ui.core/tree/rel-1.26/resources/sap/ui

you can find "test" directory - do you know what is the source for the inconsistency?

**Comment by RaYell** [comment]
The bower packages are created based on the release ZIP files that you can download from http://openui5.org/download.html Those packages does not contain the `test` folder you refer to. It must have been removed by SAP while preparing the release package.
